---
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: 'my-tomcat'
  labels:
    app: my-tomcat-1
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  selector: 
    matchLabels:
      app: my-tomcat1
  template:
    metadata:
      labels:
        app: my-tomcat1
    spec:
      containers:
        - name: 'my-tomcat-container-1' 
          image: tomee
          ports:
            - containerPort: 8080
---
apiVersion: v1
Kind: Service
metadata:
  name: 'my-tomcat-service'
  lables: 
    app: my-tomcat-service-1'
spec:
  labels:
    app: my-tomcat1
  type: NodePort
  ports:
    - port: 8080